joy_node:
  ros__parameters:
    device_id: 0
    deadzone: 0.05
    autorepeat_rate: 20.0

teleop_node:
  ros__parameters:
    axis_linear:
      x: 1   # Left joystick up/down (could be throttle if needed)
      y: 0   # Left joystick left/right (not used)
      z: 4   # Right joystick up/down (could be secondary control)

    scale_linear:
      x: 0.5
      y: 0.5
      z: 0.5

    axis_angular:
      yaw: 3  # Right joystick left/right for rotation (not used for your car)
      
    scale_angular:
      yaw: 0.5

    enable_button: 0  # A button (Accelerate)
    brake_button: 2   # X button (Brake)
    reverse_button: 1 # B button (Reverse)
    turbo_button: 5   # RB (Right Bumper - Turbo Mode)
    slow_button: 4    # LB (Left Bumper - Slow Mode)
    start_button: 7   # Start Button
    back_button: 6    # Back Button
    joystick_left_button: 9  # Press Left Stick
    joystick_right_button: 10 # Press Right Stick

    require_enable_button: false
